{
    "openapi": "3.0.0",
    "info": {
        "title": "Orange Portfolio API",
        "description": "API da aplicação Orange Portfolio para cadastro de projetos de usuários",
        "version": "0.1.0"
    },
    "servers": [
        {
            "url": "https://orangeportfoliosquad32.software",
            "description": "production"
        },
        {
            "url": "http://localhost:3000",
            "description": "development"
        }
    ],
    "paths": {
        "/login": {
            "post": {
                "summary": "Login",
                "description": "Faz o login do usuário no sistema",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "password": {
                                        "type": "string",
                                        "required": true
                                    }
                                }
                            },
                            "examples": {
                                "login válido": {
                                    "value": {
                                        "email": "testes@gmail",
                                        "password": "senha123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "login com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "user": {
                                            "user_id": 1
                                        },
                                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJpTkkMW31yNw"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Senha incorreta",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Email ou senha Inválidos!"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/login/profile": {
            "post": {
                "summary": "Dados do usuário logado",
                "description": "Retorna algumas informações do usuário logado",
                "responses": {
                    "200": {
                        "description": "dados retornados",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "user_id": 1,
                                        "first_name": "Tiago",
                                        "last_name": "Lopes",
                                        "email": "tiagolopes@gmail.com",
                                        "avatar_id": 1
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "summary": "Cadastro de usuários",
                "description": "Cadastra usuários no sistema",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "first_name": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "last_name": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "email": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "avatar_id": {
                                        "type": "number",
                                        "required": true
                                    },
                                    "password": {
                                        "type": "string",
                                        "required": true
                                    }
                                }
                            },
                            "examples": {
                                "usuário": {
                                    "value": {
                                        "first_name": "Tiago",
                                        "last_name": "Lopes",
                                        "email": "tiagolopes@gmail.com",
                                        "avatar_id": 1,
                                        "password": "Senha123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "cadastro efetuado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string",
                                    "example": "Cadastro Feito com sucesso"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "E-mail repetido",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "status": "fail",
                                        "message": "Email already exist, please use another email address"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "summary": "Busca todos os usuários",
                "description": "Faz a busca de todos os usuários do sistema",
                "responses": {
                    "200": {
                        "description": "usuário encontrado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": [
                                        {
                                            "user_id": 1,
                                            "first_name": "Tiago",
                                            "last_name": "Lopes",
                                            "avatar_id": 1,
                                            "email": "tiagoltavares2002@gmail.com",
                                            "password": "$2b$10$bDtGRy7kPGblE4i.5DkgverwjJqEUJeWV/5ceD2hSAezGJD2N8bee"
                                        },
                                        {
                                            "user_id": 2,
                                            "first_name": "Matheus",
                                            "last_name": "Santos",
                                            "avatar_id": 1,
                                            "email": "teste@gmail.com",
                                            "password": "$2b$10$wtsKznaPZgPATxJC9vJK..IaRybabQRwn8eV/gA.87Hn35jJlbGU2"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}/projects": {
            "post": {
                "summary": "Cadastro de projetos",
                "description": "Cadastra projetos de um usuário",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID do usuário",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "title": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "description": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "link": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "tags": {
                                        "type": "object",
                                        "required": true
                                    },
                                    "image_id": {
                                        "type": "number",
                                        "required": true
                                    }
                                }
                            },
                            "examples": {
                                "usuário": {
                                    "value": {
                                        "title": "Teste de projeto",
                                        "description": "Teste de novo projeto",
                                        "link": "https://github.com/Squad-32-hackaton",
                                        "tags": ["front-end", "mobile"],
                                        "image_id": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "cadastro efetuado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "project": {
                                            "project_id": 1,
                                            "user_id": 1,
                                            "title": "Teste de projeto",
                                            "description": "Teste de novo projeto",
                                            "image_id": 1,
                                            "link": "https://github.com/Squad-32-hackaton",
                                            "createdAt": "2024-01-29T23:42:46.165Z",
                                            "updatedAt": "2024-01-29T23:42:46.165Z",
                                            "tags": ["front-end", "mobile"]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "errors": [
                                            "Field 'description' is required",
                                            "Field 'link' must be a string",
                                            "Field 'tags' must be a string array",
                                            "Field 'image_id' must be a number"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Busca todos os projetos de um usuário",
                "description": "Lista todos os projetos de um usuário buscando pelo ID do usuário.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID do usuário",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "projetos retornados com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "projects": [
                                            {
                                                "project_id": 5,
                                                "user": {
                                                    "name": "Tiago Lopes",
                                                    "avatar": "1706654310565_api.png"
                                                },
                                                "tags": [
                                                    "Front-end",
                                                    "Back-end"
                                                ],
                                                "image": "1706654310565_api.png",
                                                "creationDate": "01/24"
                                            },
                                            {
                                                "project_id": 2,
                                                "user": {
                                                    "name": "Tiago Lopes",
                                                    "avatar": "1706654310565_api.png"
                                                },
                                                "tags": ["Teste"],
                                                "image": "1706654310565_api.png",
                                                "creationDate": "01/24"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}/searchProjects": {
            "get": {
                "summary": "Filtra projetos do usuário por tag",
                "description": "Exibe todos os projetos do usuário que contém uma tag específica",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "description": "ID do usuário",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "tag",
                        "in": "query",
                        "description": "Tag que os projetos devem conter",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "projetos contendo a tag retornados com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "projects": [
                                            {
                                                "project_id": 5,
                                                "user": {
                                                    "name": "Tiago Lopes",
                                                    "avatar": "1706654310565_api.png"
                                                },
                                                "tags": [
                                                    "Front-end",
                                                    "Back-end"
                                                ],
                                                "image": "1706654310565_api.png",
                                                "creationDate": "01/24"
                                            },
                                            {
                                                "project_id": 1,
                                                "user": {
                                                    "name": "Tiago Lopes",
                                                    "avatar": "1706654310565_api.png"
                                                },
                                                "tags": ["front-end", "mobile"],
                                                "image": "1706654310565_api.png",
                                                "creationDate": "01/24"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "errors": [
                                            "Param 'user_id' must be a number",
                                            "Query string 'tag' is required"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "summary": "Busca projetos de outros usuários",
                "description": "Exibe todos os projetos de outros usuários do sistema.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "projetos retornados com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "projects": [
                                            {
                                                "project_id": 7,
                                                "user": {
                                                    "name": "Fernando José",
                                                    "avatar": null
                                                },
                                                "link": "https://orangeportfoliosquad32.software",
                                                "tags": [
                                                    "Front-end",
                                                    "Back-end"
                                                ],
                                                "image": "1706654310565_api.png",
                                                "creationDate": "01/24"
                                            },
                                            {
                                                "project_id": 6,
                                                "user": {
                                                    "name": "Tiago Silva",
                                                    "avatar": "1706654310565_api.png"
                                                },
                                                "link": "https://orangeportfoliosquad32.software",
                                                "tags": [
                                                    "Front-end",
                                                    "Back-end"
                                                ],
                                                "image": "1706654310565_api.png",
                                                "creationDate": "01/24"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/projects/{id}": {
            "get": {
                "summary": "Detalhes de um projeto",
                "description": "Exibe todos os detalhes de um projeto.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID do projeto",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "projeto retornado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "project": {
                                            "project_id": 1,
                                            "user": {
                                                "name": "Tiago Lopes",
                                                "avatar": "1706654310565_api.png"
                                            },
                                            "title": "Teste de projeto",
                                            "description": "Teste de novo projeto",
                                            "link": "https://github.com/Squad-32-hackaton",
                                            "tags": ["front-end", "mobile"],
                                            "image": "1706654310565_api.png",
                                            "creationDate": "01/24"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "projeto não encontrado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Project not found"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/searchProjects": {
            "get": {
                "summary": "Filtra projetos de outros usuários por tag",
                "description": "Exibe todos os projetos de outros usuário que contém uma tag específica",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "tag",
                        "in": "query",
                        "description": "Tag que os projetos devem conter",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "projetos contendo a tag retornados com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "projects": [
                                            {
                                                "project_id": 7,
                                                "user": {
                                                    "name": "Fernando José",
                                                    "avatar": null
                                                },
                                                "link": "https://orangeportfoliosquad32.software",
                                                "tags": [
                                                    "Front-end",
                                                    "Back-end"
                                                ],
                                                "image": "1706654310565_api.png",
                                                "creationDate": "01/24"
                                            },
                                            {
                                                "project_id": 6,
                                                "user": {
                                                    "name": "Tiago Silva",
                                                    "avatar": "1706654310565_api.png"
                                                },
                                                "link": "https://orangeportfoliosquad32.software",
                                                "tags": [
                                                    "Front-end",
                                                    "Back-end"
                                                ],
                                                "image": "1706654310565_api.png",
                                                "creationDate": "01/24"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "errors": [
                                            "Query string 'tag' is required"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "description": "Autenticação utilizando JWT",
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}
